[options]
admin_passwd = $pbkdf2-sha512$600000$HWPsnVNKybkX4nyP8b73fg$4EV1kB15L.ehlbWuoDxdGIEDTaQfy3ei5/tg8dqrmmKOoMUOCXN16tucWzkgjJx5.hk4yfpc7mj8tHGUBq.DxA
addons_path = odoo-e/odoo/addons,odoo-c/addons,odoo-c/odoo/addons
db_host = localhost
db_port = 5432
db_user = odoo
db_password = odoo
list_db = True
db_sslmode = prefer
db_maxconn = 64
http_interface = 127.0.0.1
http_port = 8069
proxy_mode = False
dev_mode = reload,qweb,xml
logfile = 
log_level = info
log_handler = :INFO
workers = 0
max_cron_threads = 1
limit_time_cpu = 600
limit_time_real = 1200
limit_memory_soft = 2147483648
limit_memory_hard = 2684354560
without_demo = False
test_enable = False
csv_internal_sep = ,

